# Generated by Django 5.0.3 on 2024-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hidden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
